//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace ActionListMessage {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ActionList {
        
        private ActionListHeader headerField;
        
        private ActionListActionList[] actionList1Field;
        
        /// <remarks/>
        public ActionListHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionList")]
        public ActionListActionList[] ActionList1 {
            get {
                return this.actionList1Field;
            }
            set {
                this.actionList1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ActionListHeader {
        
        private string hostNameField;
        
        private bool isAbortField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsAbort {
            get {
                return this.isAbortField;
            }
            set {
                this.isAbortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ActionListActionList {
        
        private Position positionField;
        
        private GameMode gameModeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Position Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public GameMode GameMode {
            get {
                return this.gameModeField;
            }
            set {
                this.gameModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    public enum Position {
        
        /// <remarks/>
        A1,
        
        /// <remarks/>
        A2,
        
        /// <remarks/>
        A3,
        
        /// <remarks/>
        A4,
        
        /// <remarks/>
        A5,
        
        /// <remarks/>
        A6,
        
        /// <remarks/>
        A7,
        
        /// <remarks/>
        A8,
        
        /// <remarks/>
        B1,
        
        /// <remarks/>
        B2,
        
        /// <remarks/>
        B3,
        
        /// <remarks/>
        B4,
        
        /// <remarks/>
        B5,
        
        /// <remarks/>
        B6,
        
        /// <remarks/>
        B7,
        
        /// <remarks/>
        B8,
        
        /// <remarks/>
        C1,
        
        /// <remarks/>
        C2,
        
        /// <remarks/>
        C3,
        
        /// <remarks/>
        C4,
        
        /// <remarks/>
        C5,
        
        /// <remarks/>
        C6,
        
        /// <remarks/>
        C7,
        
        /// <remarks/>
        C8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    public enum GameMode {
        
        /// <remarks/>
        SetUp,
        
        /// <remarks/>
        Mark,
        
        /// <remarks/>
        Move,
        
        /// <remarks/>
        Remove,
        
        /// <remarks/>
        Remove2,
        
        /// <remarks/>
        Jump,
        
        /// <remarks/>
        End,
    }
}
