name: NineMensMorris

on:
    pull_request:
        branches: ['main']
        paths:
            - 'NineMensMorris/NineMensMorris'
    
    workflow_dispatch:

jobs:

    build:
        runs-on: windows-latest

        steps:     
            - uses: actions/checkout@v4

            - name: MsBuild setup
              uses: microsoft/setup-msbuild@v1.1
            
            - name: Build Nine Mens Morris
              run: msbuild NineMensMorris\NineMensMorris\NineMensMorris.csproj -t:rebuild -property:Configuration=Release

            - uses: actions/upload-artifact@v4
              with:
                name: Upload Artifact NineMensMorris.exe
                path: NineMensMorris\NineMensMorris\bin\Release\NineMensMorris.exe
                
