name: SqlScriptRunner

on:
    pull_request:
        branches: ['main']
        paths:
            - 'SqlScriptRunner/SqlScriptRunner'
            - 'SqlScriptRunner/UsersGuide'
    
    workflow_dispatch:

jobs:
#    build:
#        runs-on: windows-latest
#        steps:
#            - name: CheckOut
#              uses: actions/checkout@v3
#            - name: MsBuild setup
#              uses: microsoft/setup-msbuild@v1.1
#            
#            - name: Build SQL Scrip Runner
#              run: msbuild SqlScriptRunner\SqlScriptRunner\SqlScriptRunner.csproj -t:rebuild -property:Configuration=Release
#                  
#            - uses: actions/upload-artifact@v4
#              with:
#                name: Upload Artifact SqlScriptRunner.exe
#                path: SqlScriptRunner\SqlScriptRunner\bin\Release\SqlScriptRunner.exe

    convert_via_pandoc:
          runs-on: ubuntu-latest
          steps:
            - name: CheckOut
              uses: actions/checkout@v3
            - name: Build Users guide
              uses: docker://pandoc/latex:2.9
              with:
                args: >-
                  --from markdown+rebase_relative_paths
                  --to pdf
                  --output=UsersGuide.pdf
                  --standalone
                  --data-dir=./SqlScriptRunner/UsersGuide
                  ./SqlScriptRunner/UsersGuide/UsersGuide.md    
            - uses: actions/upload-artifact@v4
              with:
                name: Upload Artifact UsersGuide
                path: UsersGuide.pdf
