name: SqlScriptRunner

on:
    pull_request:
        branches: ['main']
        paths:
            - 'SqlScriptRunner/SqlScriptRunner'
            - 'SqlScriptRunner/UsersGuide'
    
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: CheckOut
              uses: actions/checkout@v3
            - name: MsBuild setup
              uses: microsoft/setup-msbuild@v1.1
            
            - name: Build SQL Scrip Runner
              run: msbuild SqlScriptRunner\SqlScriptRunner\SqlScriptRunner.csproj -t:rebuild -property:Configuration=Release
                  
            - uses: actions/upload-artifact@v4
              with:
                name: ArtifactSqlScriptRunner
                path: SqlScriptRunner\SqlScriptRunner\bin\Release\SqlScriptRunner.exe

    build_user_guide:
          runs-on: ubuntu-latest
          steps:
            - name: CheckOut
              uses: actions/checkout@v3
            - name: Build Users guide
              uses: docker://pandoc/latex:latest
              with:
                args: >-
                  --from markdown+rebase_relative_paths
                  --to pdf
                  --output=UsersGuide.pdf
                  --standalone
                  --data-dir=./SqlScriptRunner/UsersGuide
                  ./SqlScriptRunner/UsersGuide/UsersGuide.md    
            - uses: actions/upload-artifact@v4
              with:
                name: ArtifactUsersGuide
                path: UsersGuide.pdf
    
    build_install_package:
        runs-on: windows-latest
        needs: [build, build_user_guide]
        steps:
        - name: Install NSIS
          run: |
            iwr -useb get.scoop.sh -outfile 'install.ps1'
            .\install.ps1 -RunAsAdmin
            scoop update
            scoop bucket add extras
            scoop install nsis
        - name: Print NSIS version
          run: makensis -VERSION
        - name: CheckOut
          uses: actions/checkout@v3
        - uses: actions/download-artifact@master
          with:
            name: ArtifactSqlScriptRunner
            path: SqlScriptRunner\SqlScriptRunner\bin\Release\
        - uses: actions/download-artifact@master
          with:
            name: ArtifactUsersGuide
            path: SqlScriptRunner\
        
        # TODO: create a new artifact
        - name: Create install package
          run: makensis .\SqlScriptRunner\Installer\SqlScripRunnerSetup.nsi
        - uses: actions/upload-artifact@v4
          with:
            name: SqlScriptRunnerSetup
            path: .\SqlScriptRunner\Installer\SqlScriptRunnerSetup.exe
            
